### ISSUE TITLE
Make the project direction more modular

### ISSUE THREAD

**Issue by hjwylde** [hjwylde/git-fmt#38]
Rather than having quite rigid requirements on pretty instances (e.g., tabs and maximum 100 character line length), make this tool modular in that it uses other binaries for pretty printing.

A configuration file can be used to define delegates and this tool can hook them together with a git repository by providing statuses and dry-runs.

(Thanks @purcell for the feedback!)

**Comment by hjwylde** [comment]
I'm thinking the configuration file should be completely ambivalent to the target pretty printers. It could do this by using string replacement for the input file name and the output file name.

E.g.,

``` yaml
json_pp:
    extensions: ["json"]
    command: "cat {{inputFile}} | json_pp > {{outputFile}}"
```

**Comment by purcell** [comment]
Suggestions...

Bundled config:

``` yaml
...
json_pp:
    extensions: ["json"]
    command: "cat {{inputFile}} | json_pp > {{outputFile}}"
    enabled: true
...
```

Project-specific:

``` yaml
...
json_pp:
    extensions: ["json", "jsn"]
css_tidy:
    enabled: false
```
