### ISSUE TITLE
How should we handle specifying specific versions of binaries?

### ISSUE THREAD

**Issue by hjwylde** [hjwylde/git-fmt#45]
hjwylde/omnifmt#6

**Comment by hjwylde** [comment]
I think having a dependencies section could work. E.g.,
```
json:
    extensions: ["json"]
    command: "json_pp"
    dependencies:
    - name: "json_pp"
      version-flag: "-v"
      constraint: "^1\."
```

That way I can give nicer warnings when a command is missing. It can also be optional to make it easier to just get `git-fmt` working out of the box.

Tossing up whether `constraint` should be a regular expression or if the `version-flag` should be made to return a specific format. Main issue here is that binaries often return versions in very different formats.
